#
# Your Crowdin credentials
#
"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true
#
# Files configuration
#
files: [
  {
    "source": "/email-connector-webapps/src/main/resources/locale/portlet/emailConnector/emailConnectorAdministration_en.properties",
    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace": { YML_CROWDIN_LANGUAGES_ARG },
    "dest": "add__ons/email__connector/emailConnectorAdministration.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  {
    "source": "/email-connector-webapps/src/main/resources/locale/portlet/emailConnector/emailConnectorUserSetting_en.properties",
    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace": { YML_CROWDIN_LANGUAGES_ARG },
    "dest": "add__ons/email__connector/emailConnectorUserSetting.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  {
    "source": "/email-connector-webapps/src/main/resources/locale/portlet/emailConnector/emailConnectorMailBox_en.properties",
    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace": { YML_CROWDIN_LANGUAGES_ARG },
    "dest": "add__ons/email__connector/emailConnectorMailBox.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  {
    "source" : "/email-connector-webapps/src/main/resources/locale/portlet/QuickActions_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/email__connector/QuickActions.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/email-connector-webapps/src/main/resources/locale/addon/appcenter_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/email__connector/appcenter.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/email-connector-webapps/src/main/resources/locale/portlet/Analytics_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/email__connector/Analytics.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
]
