<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.exoplatform.addons.email-connector</groupId>
    <artifactId>email-connector-parent</artifactId>
    <version>7.2.0-M11</version>
  </parent>
  <artifactId>email-connector-services</artifactId>
  <name>eXo Email Connector - Services</name>
  <properties>
    <exo.test.coverage.ratio>0.5</exo.test.coverage.ratio>
  </properties>
  <dependencies>
    <dependency>
      <groupId>io.meeds.social</groupId>
      <artifactId>social-component-service</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.social</groupId>
      <artifactId>social-component-notification</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.app-center</groupId>
      <artifactId>app-center-services</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.analytics</groupId>
      <artifactId>analytics-api</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
